[package]
name = "shards-ml"
description = ""
license = "BSD-3-Clause"
version = "0.1.0"
authors = ["Giovanni Petrantoni <sinkingsugar@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
lazy_static = "1.5.0"
shards = { path = "../../rust" }
compile-time-crc32 = "0.1.2"
tokenizers = { version = "0.19.1", default-features = false, features = [
  "onig",
] }

candle-core = { version = "0.6.0" }
candle-transformers = { version = "0.6.0" }
candle-nn = { version = "0.6.0" }
# candle-core = { version = "0.6.0", git = "https://github.com/sinkingsugar/candle-wgpu.git", rev = "c8f4701f83d523b40c70075fabbd10028e04d049" }
# candle-transformers = { version = "0.6.0", git = "https://github.com/sinkingsugar/candle-wgpu.git", rev = "c8f4701f83d523b40c70075fabbd10028e04d049" }
# candle-nn = { version = "0.6.0", git = "https://github.com/sinkingsugar/candle-wgpu.git", rev = "c8f4701f83d523b40c70075fabbd10028e04d049" }

serde_json = "1.0.102"
once_cell = "1.9.0"

[features]
default = []
metal = ["candle-core/metal", "candle-transformers/metal", "candle-nn/metal"]
cuda = ["candle-core/cuda", "candle-transformers/cuda", "candle-nn/cuda"]
accelerate = ["candle-core/accelerate", "candle-transformers/accelerate", "candle-nn/accelerate"]
