[package]
name = "egui-gfx"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = { version = "0.21.0" }
lazy_static = "1.4.0"

[build-dependencies]
bindgen = "0.64.0"
gfx-build = { path = "../rust/build" }

[features]
# Enables the test UI code
standalone_test = []
