[package]
name = "chainblocks"
description = "rust bindings and utility in order to use chainblocks"
license = "BSD-3-Clause"
version = "0.1.0"
authors = ["Giovanni Petrantoni <sinkingsugar@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
approx = "0.4.0"
csv = { version = "1.1.4", optional = true }

[target.'cfg(not(target_arch="wasm32"))'.dependencies]
dlopen = "0.1.8"

[target.'cfg(target_arch="wasm32")'.dependencies]
wasm-bindgen = "0.2"

[dev-dependencies]
ctor = "0.1.16"

[build-dependencies]
bindgen = "0.55.1"

[features]
default = []
dummy = []
blocks = ["csv"]
cb_static = []
cb_dynamic = []