[package]
name = "chainblocks"
description = "rust bindings and utility in order to use chainblocks"
license = "BSD-3-Clause"
version = "0.1.0"
authors = ["Giovanni Petrantoni <sinkingsugar@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]

[dependencies]
approx = "0.4.0"
lazy_static = "1.4.0"
futures =  "0.3.8"
futures-util = "0.3.8"

[target.'cfg(not(target_arch="wasm32"))'.dependencies]
dlopen = "0.1.8"
reqwest = { version = "0.10", features = ["blocking"], optional = true }

[target.'cfg(target_arch="wasm32")'.dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.18"
reqwest = { version = "0.10",optional = true }

[dev-dependencies]
ctor = "0.1.16"

[build-dependencies]
bindgen = { version = "0.55.1", optional = true }

[features]
default = []
dummy = []
blocks = ["reqwest"]
cb_static = []
cb_dynamic = []
run_bindgen = ["bindgen"]