edit_uri: ''
repo_url: https://github.com/fragcolor-xyz/shards/
site_name: Fragcolor documentation
site_url: https://docs.fragcolor.xyz
copyright: Copyright Â© 2021 Fragcolor Pte. Ltd.
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fragcolor-xyz
      name: Fragcolor is on GitHub
    - icon: fontawesome/brands/discord
      link: https://discord.gg/c7mjxvYqd3
      name: Join us on Discord
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/fragcolor
      name: Follow us on Twitter
    # - icon: fontawesome/brands/facebook
    #   link: https://www.facebook.com/fragcolor/
    #   name: Follow us on Facebook
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/company/fragcolor/
      name: Company profile on LinkedIn
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html
  - toc:
      permalink: true
plugins:
  - search:
      separator: '[\s\-\.\`]'
  - awesome-pages:
      strict: false
  - macros
extra_css:
  - style_overrides.css
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
  font:
    code: Fira Code
    text: Hind
  language: custom
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: fragnova-light
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
use_directory_urls: true
