edit_uri: ''
repo_url: https://github.com/fragcolor-xyz/chainblocks/
site_name: Fragcolor documentation
site_url: https://docs.fragcolor.xyz
copyright: Copyright Â© 2021 Fragcolor Pte. Inc.
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fragcolor-xyz
      name: Fragcolor is on GitHub
    - icon: fontawesome/brands/discord
      link: https://discord.gg/c7mjxvYqd3
      name: Join us on Discord
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/fragcolor
      name: Follow us on Twitter
    # - icon: fontawesome/brands/facebook
    #   link: https://www.facebook.com/fragcolor/
    #   name: Follow us on Facebook
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/company/fragcolor/
      name: Company profile on LinkedIn
markdown_extensions:
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
plugins:
  - search
  - awesome-pages:
      strict: false
theme:
  favicon: assets/images/logo.svg
  features:
    # - navigation.indexes # disabled: looks like there are some bugs.
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
  font:
    code: Fira Code
    text: Montserrat
  language: en
  logo: assets/images/logo.svg
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
use_directory_urls: true
