name: Build (Linux)

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: Build in Release or Debug?
        required: true
        default: Debug
        type: choice
        options:
          - Debug
          - Release
      run-tests:
        description: Run the tests?
        required: false
        default: false
        type: boolean
      rust-cache:
        description: Use existing rust cache?
        required: false
        default: false
        type: boolean
  workflow_call:
    inputs:
      build-type:
        required: true
        default: Debug
        type: string
      run-tests:
        required: false
        default: false
        type: boolean
      rust-cache:
        required: false
        default: true
        type: boolean

# Required for <compare> and <=> support
env:
  CC: gcc-11
  CXX: g++-11

jobs:
  #
  # Build shards for linux
  #
  Linux:
    name: Build (${{ github.event.inputs.build-type || inputs.build-type }})
    runs-on: ubuntu-22.04
    outputs:
      build-type: ${{ steps.setup.outputs.build-type }}
      run-tests: ${{ steps.setup.outputs.run-tests }}
      rust-cache: ${{ steps.setup.outputs.rust-cache }}
    steps:
      - name: Setup
        id: setup
        run: |
          echo "build-type=${{ github.event.inputs.build-type || inputs.build-type }}" >> $GITHUB_OUTPUT
          echo "run-tests=${{ github.event.inputs.run-tests || inputs.run-tests }}" >> $GITHUB_OUTPUT
          echo "rust-cache=${{ github.event.inputs.rust-cache || inputs.rust-cache }}" >> $GITHUB_OUTPUT
      - name: Checkout shards
        uses: actions/checkout@v3
        with:
          repository: fragcolor-xyz/shards
          fetch-depth: 2
          submodules: recursive
      - name: Set up dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install build-essential git cmake wget clang ninja-build xorg-dev libdbus-1-dev libssl-dev lcov mesa-utils
          ./bootstrap
          rustup toolchain install nightly
          rustup default nightly
      - uses: Swatinem/rust-cache@v2
        if: ${{ steps.setup.outputs.rust-cache == 'true'}}
        with:
          key: ${{ steps.setup.outputs.build-type }}
      - name: Build
        run: |
          mkdir -p build
          cd build

          if [ "${{ steps.setup.outputs.build-type }}" == "Debug" ]; then
            cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=1 -DTRACY_ENABLE=ON -DTRACY_TIMER_FALLBACK=ON ..
          else
            cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
          fi

          ninja shards
          ninja test-runtime
      - name: Test
        env:
          RUST_BACKTRACE: 1
        run: |
          cd build
          chmod +x shards
          ./shards ../src/tests/general.edn
          ./shards ../src/tests/variables.clj
          ./shards ../src/tests/subwires.clj
          ./shards ../src/tests/linalg.clj
          ./shards ../src/tests/loader.clj
          ./shards ../src/tests/network.clj
          ./shards ../src/tests/struct.clj
          ./shards ../src/tests/flows.edn
          ./shards ../src/tests/kdtree.clj
          ./shards ../src/tests/channels.clj
          ./shards ../src/tests/genetic.clj
          ./shards ../src/tests/imaging.clj
          ./shards ../src/tests/http.clj
          ./shards ../src/tests/ws.edn
          ./shards ../src/tests/bigint.clj
          ./shards ../src/tests/brotli.clj
          ./shards ../src/tests/snappy.clj
          ./shards ../src/tests/failures.clj
          ./shards ../src/tests/wasm.clj
          ./shards ../src/tests/rust.clj
          ./shards ../src/tests/crypto.edn
          ./shards ../src/tests/wire-macro.edn
          ./shards ../src/tests/edn.edn
          ./shards ../src/tests/const-vars.edn
          ./shards ../src/tests/branch.edn
          ./shards ../src/tests/audio.edn
          ./shards ../src/tests/time.edn
          ./shards ../src/tests/eth.edn
          ./shards ../src/tests/take.edn
          ./shards ../src/tests/casting-numbers.edn
          ./shards ../src/tests/edn.edn
          ./shards ../src/tests/pure.edn
          # ./shards ../src/tests/shell.clj
          ./shards ../src/tests/infos.clj
          ./shards ../src/tests/many.edn
          ./shards ../src/tests/events.edn
          ./shards ../src/tests/tablecase.edn
          ./shards ../src/tests/types.edn
          ./shards ../src/tests/complex-deserialize.edn
      - name: Test (Debug)
        # Test that only works in Debug build go there
        if: ${{ steps.setup.outputs.build-type == 'Debug' }}
        env:
          RUST_BACKTRACE: 1
        run: |
          cd build
          ./shards ../src/tests/export-strings.edn
      - name: Test doc samples (non-UI)
        env:
          RUST_BACKTRACE: 1
        run: |
          cd docs/samples
          for i in $(find shards -name '*.edn' \( ! -path '*UI*' ! -path '*GFX*' ! -path '*Dialog*' \));
          do
            echo "Running sample $i";
            ../../build/shards run-sample.edn --file "$i";
          done
      - name: Test runtime
        env:
          RUST_BACKTRACE: 1
        run: |
          cd build
          ./test-runtime
      - name: Collect coverage (Debug)
        if: ${{ steps.setup.outputs.build-type == 'Debug' }}
        run: |
          mkdir coverage
          # capture
          lcov \
            --capture \
            --directory build/src \
            --output-file coverage/coverage.info
          # remove external dependencies
          lcov \
            --remove coverage/coverage.info "*/c++/*" "*/boost/*" "*/usr/*" "*/deps/*" "*/src/mal/*" \
            --output-file coverage/coverage.linux.info
          # convert absolute path to relative path
          sed -i s/${PWD////\\/}/./g coverage/coverage.linux.info
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: shards-linux ${{ steps.setup.outputs.build-type }}
          path: build/shards
          if-no-files-found: error
      - name: Upload coverage (Debug)
        if: ${{ steps.setup.outputs.build-type == 'Debug' }}
        uses: actions/upload-artifact@v3
        with:
          name: shards-linux-coverage
          path: coverage/coverage.linux.info
          if-no-files-found: error
