name: Build (Linux)

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: Build in Release or Debug?
        required: true
        default: Debug
        type: choice
        options:
          - Debug
          - Release
      run-tests:
        description: Run the tests?
        required: false
        default: false
        type: boolean
      run-extra-tests:
        description: Run the extra tests (Debug only)?
        required: false
        default: false
        type: boolean
  workflow_call:
    inputs:
      build-type:
        required: true
        default: Debug
        type: string
      run-tests:
        required: false
        default: false
        type: boolean
      run-extra-tests:
        required: false
        default: false
        type: boolean

jobs:
  #
  # Build shards for linux
  #
  Linux:
    name: Build (${{ github.event.inputs.build-type || inputs.build-type }})
    runs-on: ubuntu-latest
    outputs:
      run-tests: ${{ steps.setup.outputs.run-tests }}
      run-extra-tests: ${{ steps.setup.outputs.run-extra-tests }}
    steps:
      - name: Setup
        id: setup
        run: |
          echo "::set-output name=build-type::${{ github.event.inputs.build-type || inputs.build-type }}"
          echo "::set-output name=run-tests::${{ github.event.inputs.run-tests || inputs.run-tests }}"
          echo "::set-output name=run-extra-tests::${{ github.event.inputs.run-extra-tests || inputs.run-extra-tests }}"
      - name: Checkout shards
        uses: actions/checkout@v3
        with:
          repository: fragcolor-xyz/shards
          fetch-depth: 1
          submodules: recursive
      - name: Set up dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install build-essential git cmake wget clang ninja-build xorg-dev libdbus-1-dev libssl-dev mesa-utils
          ./bootstrap
          rustup toolchain install nightly
          rustup default nightly
      - uses: Swatinem/rust-cache@v1
        if: ${{ github.event_name != 'workflow_dispatch' }}
        with:
          key: ${{ steps.setup.outputs.build-type }}
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=${{ steps.setup.outputs.build-type }} ..
          ninja shards
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: shards-linux ${{ steps.setup.outputs.build-type }}
          path: build/shards
          if-no-files-found: error

  #
  # Test and coverage on linux
  #
  Linux-test:
    if: ${{ needs.Linux.outputs.run-tests == 'true' }}
    needs: Linux
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        id: setup
        run: |
          echo "::set-output name=build-type::${{ github.event.inputs.build-type || inputs.build-type }}"

          if [ "${{ github.event.inputs.build-type || inputs.build-type }}" == "Debug" ]
          then
            echo "::set-output name=submodules::recursive"
          else
            echo "::set-output name=submodules::false"
          fi
      - name: Checkout shards
        uses: actions/checkout@v3
        with:
          repository: fragcolor-xyz/shards
          fetch-depth: 2
          submodules: ${{ steps.setup.outputs.submodules }}
      - name: Set up dependencies (Debug)
        if: ${{ steps.setup.outputs.build-type == 'Debug' }}
        run: |
          sudo apt-get -y update
          sudo apt-get -y install build-essential git cmake wget clang ninja-build xorg-dev libdbus-1-dev libssl-dev lcov mesa-utils
          ./bootstrap
          rustup toolchain install nightly
          rustup default nightly
      - uses: Swatinem/rust-cache@v1
        if: ${{ github.event_name != 'workflow_dispatch' }}
        with:
          key: ${{ steps.setup.outputs.build-type }}
      - name: Build (Debug)
        if: ${{ steps.setup.outputs.build-type == 'Debug' }}
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=1 ..
          ninja shards
      - name: Download artifact (Release)
        if: ${{ steps.setup.outputs.build-type == 'Release' }}
        uses: actions/download-artifact@v2
        with:
          name: shards-linux ${{ steps.setup.outputs.build-type }}
          path: build
      - name: Test
        env:
          RUST_BACKTRACE: 1
        run: |
          cd build
          chmod +x shards
          ./shards ../src/tests/general.edn
          ./shards ../src/tests/variables.clj
          ./shards ../src/tests/subwires.clj
          ./shards ../src/tests/linalg.clj
          ./shards ../src/tests/loader.clj
          ./shards ../src/tests/network.clj
          ./shards ../src/tests/struct.clj
          ./shards ../src/tests/flows.edn
          ./shards ../src/tests/kdtree.clj
          ./shards ../src/tests/channels.clj
          ./shards ../src/tests/genetic.clj
          ./shards ../src/tests/imaging.clj
          ./shards ../src/tests/http.clj
          ./shards ../src/tests/ws.edn
          ./shards ../src/tests/bigint.clj
          ./shards ../src/tests/brotli.clj
          ./shards ../src/tests/snappy.clj
          ./shards ../src/tests/failures.clj
          ./shards ../src/tests/wasm.clj
          ./shards ../src/tests/shell.clj
          ./shards ../src/tests/rust.clj
          ./shards ../src/tests/crypto.edn
          ./shards ../src/tests/wire-macro.edn
          ./shards ../src/tests/edn.edn
          ./shards ../src/tests/const-vars.edn
          ./shards ../src/tests/branch.edn
          ./shards ../src/tests/audio.edn
          ./shards ../src/tests/time.edn
          ./shards ../src/tests/eth.edn
          ./shards ../src/tests/take.edn
          ./shards ../src/tests/casting_numbers.edn
      - name: Test (Debug)
        # Test that only works in Debug build go there
        if: ${{ steps.setup.outputs.build-type == 'Debug' }}
        env:
          RUST_BACKTRACE: 1
        run: |
          cd build
          ./shards ../src/tests/shards.clj
      - name: Test samples (doc)
        if: ${{ steps.setup.outputs.build-type == 'Debug' }}
        env:
          RUST_BACKTRACE: 1
        run: |
          cd docs/samples
          for i in $(find shards -name '*.edn' ! -path '*GUI*');
          do
            echo "Running sample $i";
            ../../build/shards run_sample.edn --file "$i";
          done
      - name: Test Headless (gfx_window)
        uses: chainblocks/xvfb-action@master
        if: ${{ false }} # Failed to create vulkan backend on github runner
        with:
          working-directory: ./build
          run: ./shards ../src/tests/gfx_window.edn
      - name: Test Headless (gfx_cube)
        uses: chainblocks/xvfb-action@master
        if: ${{ false }} # Failed to create vulkan backend on github runner
        with:
          working-directory: ./build
          run: ./shards ../src/tests/gfx_cube.edn
      - name: Test Headless (gfx_materials)
        uses: chainblocks/xvfb-action@master
        if: ${{ false }} # Failed to create vulkan backend on github runner
        with:
          working-directory: ./build
          run: ./shards ../src/tests/gfx_materials.edn
      - name: Test Headless (imgui_demo)
        uses: chainblocks/xvfb-action@master
        if: ${{ false }} # Failed to create vulkan backend on github runner
        with:
          working-directory: ./build
          run: ./shards ../src/tests/imgui_demo.edn
      - name: Coverage (Debug)
        if: ${{ steps.setup.outputs.build-type == 'Debug' }}
        run: |
          mkdir coverage
          lcov --capture --directory build/src/core/CMakeFiles/shards-core-static.dir --directory build/src/mal/CMakeFiles/shards.dir --directory build/src/extra/CMakeFiles --output-file coverage/coverage.info
          lcov --remove coverage/coverage.info "*/c++/*" "*/boost/*" "*/usr/*" "*/deps/*" "*/src/mal/*" --output-file coverage/coverage.f.info
          genhtml coverage/coverage.f.info --output-directory coverage/output
          bash <(curl -s https://codecov.io/bash) -f coverage/coverage.f.info || echo "Codecov did not collect coverage reports"
      - name: Upload coverage
        if: ${{ steps.setup.outputs.build-type == 'Debug' }}
        uses: actions/upload-artifact@v2
        with:
          name: shards-linux-coverage
          path: coverage
          if-no-files-found: error

  #
  # Extra tests and coverage on linux
  #
  Linux-test-extra:
    if: ${{ needs.Linux.outputs.run-extra-tests == 'true' }}
    needs: Linux
    name: Extra Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout shards
        uses: actions/checkout@v3
        with:
          repository: fragcolor-xyz/shards
          fetch-depth: 2
          submodules: recursive
      - name: Checkout glTF-Sample-Models
        uses: actions/checkout@v3
        with:
          repository: KhronosGroup/glTF-Sample-Models
          path: external/glTF-Sample-Models
          fetch-depth: 1
      - name: Set up dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install build-essential git cmake wget clang ninja-build xorg-dev libdbus-1-dev libssl-dev lcov mesa-utils unzip
          ./bootstrap
          rustup toolchain install nightly
          rustup default nightly
      - uses: Swatinem/rust-cache@v1
        if: ${{ github.event_name != 'workflow_dispatch' }}
        with:
          key: ${{ steps.setup.outputs.build-type }}
      - name: Build
        run: |
          cmake -Bbuild -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=1 -DSHARDS_BUILD_TESTS=1
          cd build
          ninja test_runtime && ninja test_gfx
      - name: Test runtime
        env:
          RUST_BACKTRACE: 1
        run: |
          cd build
          ./test_runtime
      - name: Test graphics
        uses: chainblocks/xvfb-action@master
        if: ${{ false }} # Failed to create vulkan backend on github runner
        with:
          working-directory: ./build
          run: |
            ./test_gfx
      - name: CodeCov
        run: |
          mkdir coverage
          lcov --capture --directory build/src/core/CMakeFiles/shards-core-static.dir --directory build/src/core/CMakeFiles/test_runtime.dir --directory build/src/extra/CMakeFiles --directory build/src/gfx --output-file coverage/coverage.info
          lcov --remove coverage/coverage.info "*/c++/*" "*/boost/*" "*/usr/*" "*/deps/*" "*/src/mal/*" --output-file coverage/coverage.f.info
          genhtml coverage/coverage.f.info --output-directory coverage/output
          bash <(curl -s https://codecov.io/bash) -f coverage/coverage.f.info || echo "Codecov did not collect coverage reports"
      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: shards-linux-coverage-extra
          path: coverage
          if-no-files-found: error
